### ISSUE TITLE
Marcar reunião com Cinthia

### ISSUE THREAD

**Issue by prgs1** [aplneto/medmapper#12]
Nova stakeholder do projeto, do Departamento de Pediatria/Fisioterapia.

**Comment by aplneto** [comment]
[Áudio da Reunião](https://drive.google.com/file/d/1j9yu_FFqctwZD2BFjVF2-fOuBZN4xa9Y/view?usp=sharing);
[Transcrição da Reunião](https://docs.google.com/document/d/1dYCjrR9QwDgm3IXj4i7NUlOM1jOuhYRZ5jz6MoKH9gQ/edit?usp=sharing)

**Comment by prgs1** [comment]
deixar aberto pra marcar a próxima reunião

**Comment by aplneto** [comment]
Próxima reunião será marcada depois da #17

**Comment by prgs1** [comment]
as reuniões estão fixadas nas quartas-feiras pela manhã, 10h.
