### ISSUE TITLE
Transcrever áudio da primeira reunião com Cinthia

### ISSUE THREAD

**Issue by prgs1** [aplneto/medmapper#14]
para podermos termos uma noção inicial das expectativas do cliente

**Comment by aplneto** [comment]
#13: [Doc](https://docs.google.com/document/d/1dYCjrR9QwDgm3IXj4i7NUlOM1jOuhYRZ5jz6MoKH9gQ/edit?usp=sharing)
[Cinthia Vasconcelos - meeting 1.pdf](https://github.com/aplneto/medmapper/files/3032082/Cinthia.Vasconcelos.pdf "Ata da Reunião 1")
