### ISSUE TITLE
Elaboração de um formulários com perguntas para o cliente

### ISSUE THREAD

**Issue by isacits** [aplneto/medmapper#21]

**Comment by prgs1** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSdKOGfgjoitfZS8F6BhccmII0sHMU3YnCCNoZykCwluGNRZdA/viewform - cliente

https://docs.google.com/forms/d/e/1FAIpQLSd9aEFcKgugViLt4ous9Vx0ke0h660tG0OiBlXmKYsM-oBUTA/viewform - publico alvo

**Comment by aplneto** [comment]
@isacits, remover a pergunta duplicada no primeiro form.
