### ISSUE TITLE
Elaboração do site do grupo "GranDia"

### ISSUE THREAD

**Issue by aplneto** [aplneto/medmapper#22]
O site ficará no repositório [GranDia](https://github.com/aplneto/GranDia), usará uma estrutura de blogs (HTML 5 default) ou uma das estruturas abaixo.

![home](https://colorlib.com/wp/wp-content/uploads/sites/2/medica-free-template.jpg "Home")
![departamentalization](https://cdn.athemes.com/wp-content/uploads/healthflex-theme.jpg "Divisão de Departamentos/Páginas")
![service](https://line25.com/wp-content/uploads/2016/03/Clinico-Premium-Medical-and-Health-Theme.jpg "Serviços Disponíveis")

**Comment by aplneto** [comment]
Solicitação de identidade visual: logo do grupo GranDia, logo do laboratório LACAF;
Esquema de cores {fundo branco, vermelho em destaque, amarelo como cor secundária};

**Comment by prgs1** [comment]
a issue foi abortada, por fugir do escopo
