### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by aplneto** [aplneto/medmapper#29]
Lista de Assets e Collections:

### navigation
  - [x] _navbar.html.slim
  - [x] _footer.html.slim
  - [x] _header.html.slim

### comments
  - [x] _comment.html.slim
  - [x] _form.html.slim

### health_units
  - [x] _form.html.slim
  - [x] _edit_form.html.slim
  - [x] _health_unit.html.slim

### user_profile
  - [x] _form.html.slim
  - [x] _edit_form.html.slim
  - [x] _user_profile.html.slim

### professional_profile
  - [x] _form.html.slim
  - [x] _edit_form.html.slim
  - [x] _user_profile.html.slim

### service_provider
  - [x] _form.html.slim
  - [x] _edit_form.html.slim
  - [x] _user_profile.html.slim

**Comment by aplneto** [comment]
[How to stub authentication](https://github.com/plataformatec/devise/wiki/How-To:-Stub-authentication-in-controller-specs)

**Comment by aplneto** [comment]
@isacits, @GabrielCavalcanti13, quando criar testes de comportamento para as views tenham certeza de conseguir dar stub nos métodos de autenticação que vocês vão testar (log in, sign in, log out...).

**Comment by GabrielCavalcanti13** [comment]
Eu e Isac já começamos. Estamos trabalhando na branch its

**Comment by prgs1** [comment]
o _form das unidades de saúdes serão todos redirecionados para a de health_units, @GabrielCavalcanti13 , pra ficar mais dry

**Comment by aplneto** [comment]
fecgadi en da52744b126dd4dd2c2dfd74082bc55830372bf5
