### ISSUE TITLE
Elaboração do Questionário

### ISSUE THREAD

**Issue by aplneto** [aplneto/medmapper#3]
Deverá ser elaborado um questionário para envio ao Professor Vinícius, Professora Cinthia e a Associação de Mães de Anjo. O questionário deverá conter perguntas relevantes a elaboração das funcionalidades para a plataforma.
O questionário deve ser elaborado o quanto antes!

**Comment by aplneto** [comment]
As questões devem ser objetivas e simples, de modo a mapear o problema e localizar as ações a serem empregadas no desenvolvimento da aplicação para resolução do mesmo.
Sugiro uma abordagem com a apresentação das ideias de funcionalidades a serem inseridas no aplicativo, após escolha das funcionalidades críticas (ver issue #17) e uma notação em escala de 1 a 5 (sendo 1 discordo completamente e 5 concordo completamente) sobre os possíveis benefícios da aplicação.
Possivelmente um campo de comentário e a versão física (impressa) e digital (Google Form) do [documento](https://docs.google.com/document/d/1KtepqvtVFhaFH9bhvpiRuf9c3qdPHD8K1URgAPO3PdE/edit?usp=sharing "Documento para elaboração do Questionário").

**Comment by prgs1** [comment]
A proposta inicial de questionário foi passado para as clientes na reunião do dia 10/04.

Elas irão verificar e validar com outros usuários, afim de finalizarmos essa tarefa.

**Comment by aplneto** [comment]
Aguardando resposta da cliente

**Comment by aplneto** [comment]
Cliente não deu retorno sobre o questionário, então começaremos a implementação das views tentando usar uma abordagem mais user friendly possível.
