### ISSUE TITLE
Criação da autenticação

### ISSUE THREAD

**Issue by prgs1** [aplneto/medmapper#35]
Como não será mais possível a utilização do devise por conta do heroku, será necessária a implementação de um módulo de autenticação.

**Comment by aplneto** [comment]
Precisamos decidir como será feita a autenticação de usuário, se escreveremos nós mesmos ou usaremos alguma gem (sugestões: [devise], [omniauth]).

Tópicos principais:

- [ ] E-mail de confirmação
- [ ] Login por redes sociais

[devise]: https://github.com/plataformatec/devise
[omniauth]: https://github.com/omniauth/omniauth

**Comment by prgs1** [comment]
por mim a gente faz, é simples.

**Comment by aplneto** [comment]
Se for só login e senha, sim, mas se for um login com algumas etapas mais complexas (confirmação de e-mail, rede social, autenticação de dois fatores) é um pouco mais complicado.
Tem que ver o que cabe implementar

**Comment by prgs1** [comment]
acho que isso deve ser visto com o cliente

Best regards,
*Pedro Rodolfo de Souza <http://lattes.cnpq.br/2265855538164590>*
*[image: LinkedIn]
<https://www.linkedin.com/in/pedro-rodolfo-de-souza-12988835/>    [image:
Github] <https://github.com/prgs1>      [image: WhatsApp]
<https://api.whatsapp.com/send?phone=5581997068582&text=Ol%C3%A1%2C%20tudo%20bem%3F>*
Student - Information Systems, at CIn/UFPE
Internship in Computer Networks and User Support, at CIn/UFPE
Teaching assistant in Differential and Integral Calculus I (2018.1, 2018.2)
Teaching assistant in Computer Networks (2019.1)
+55 81 2126 8430 ext. 4017

Hitherto hath the Lord helped us. (1Sm 7:12)

**Comment by aplneto** [comment]
Devise autenticação, confirmação e recuperação configurados
