### ISSUE TITLE
Public Folder

### ISSUE THREAD

**Issue by aplneto** [aplneto/medmapper#37]
A pasta Public deve conter tudo o que é de acesso público aos usuários. Segue lista de sugestões.

- [x] [Erros](https://www.restapitutorial.com/httpstatuscodes.html)
- [x] 404.html;
- [x] 500.html;
- [x] 422.html;
- [x] 403.html;
- [x] Termos e Condições;
- [x] Boas vindas;
- [x] About;
- [x] Contact;
- [x] Desenvolvedores;
- [x] Favicon;
- [x] [robots.txt]

[robots.txt]: http://www.robotstxt.org/robotstxt.html, 'instructions about the pages to web robots'
[partials]: https://www.rubyguides.com/2019/04/rails-render/, 'ver "how to render partials"'

**Comment by aplneto** [comment]
Decidam se as páginas serão estáticas (.html) ou dinâmicas (.slim)

**Comment by prgs1** [comment]
isso é besteira, eu faço, em html

**Comment by prgs1** [comment]
na verdade algumas já tão prontas estáticas

**Comment by aplneto** [comment]
Okay. Marca as que forem ficando prontas e pode fechar a issue quando tudo estiver okay.

**Comment by prgs1** [comment]
422 realmente é necessário?

acho q um q podia (e deve) entrar na lista é o 403 (forbidden)

**Comment by aplneto** [comment]
@prgs1, lembra de ir atualizando a issue a medida que vai criando.

Adendum:

```ruby
# use num controller pra renderizar uma página estática com o wrapper do application.html

class Pages < ApplicationController
  def terms
    render file: "public/terms.html", layout: true
  end
end

```
