### ISSUE TITLE
Usuário-Profisional

### ISSUE THREAD

**Issue by aplneto** [aplneto/medmapper#41]
Model Usuário Profissional herda de Model Usuário e conterás as adições sugeridas em ata de reunião do dia 8 de Maio.

Modelo:
- [x] Profissão (string, obrigatório)
- [x] Registro Profissional (string, obrigatório)
- [x] Áreas de Atuação (string, multivalorado, obrigatório)
- [x] Descrição (texto)
- [x] Contatos (multivalorado, links de redes sociais)
- [x] Locais de Atuação (string, multivalorado)
- [x] Atendimento a Domicílio (booleano)

Tarefas:
- [x] Criação da Tabela
- [ ] Criação do Model

**Comment by prgs1** [comment]
done
