### ISSUE TITLE
Levantamento de unidades

### ISSUE THREAD

**Issue by aplneto** [aplneto/medmapper#51]
Já que há a possibilidade do cadastro de novas unidades de saúde por parte do usuário no banco de dados, os seguintes requisitos precisam ser levantados o controle das unidades relacionadas a órtese e prótese e unidades de saúde a serem possivelmente cadastradas pelos usuários.

**Comment by prgs1** [comment]
órtese e prótese entra no nosso escopo?

**Comment by aplneto** [comment]
Sim, levantamento de unidades que afetam portadores da CZS. Provavelmente não teremos que povoar o banco de dados com nada, mas temos que deixar a entidade pronta.

**Comment by aplneto** [comment]
Unidades que não se encaixem em uma das categorias médicas na plataforma serão cadastradas como Serviços.
