### ISSUE TITLE
Routing Specs

### ISSUE THREAD

**Issue by aplneto** [aplneto/medmapper#66]
- [x] `basic_health_units_controller`;
- [ ] `comments_controller`;
- [x] `diagnosis_units_controller`;
- [x] `emergency_units_controller`;
- [x] `family_health_units_controller`;
- [x] `health_units_controller`;
- [x] `hospitals_controller`;
- [x] `maternity_clinics_controller`;
- [x] `mental_health_units_controller`;
- [x] `odontology_units_controller`;
- [ ] `pages_controller`;
- [x] `pharmacies_controller`;
- [x] `polyclinics_controller`;
- [x] `professional_profiles_controller`;
- [x] `service_providers_controller`;
- [x] `specialized_units_controller`;
- [x] `user_profiles_controller`;
- [x] `family_health_support_centers`;

**Comment by aplneto** [comment]
@isacits, adicionei os `family_health_support_centers` a lista. Depois que concluir os testes de rota desse controlador pode fechar a issue.

**Comment by isacits** [comment]
Finalizado em c501319d0c59df6641e133bbfb020bf58f4b6645.
