### ISSUE TITLE
[Feedback] Heroku database

### ISSUE THREAD

**Issue by aacgn** [aplneto/medmapper#70]
Verifiquem esse link: https://devcenter.heroku.com/articles/sqlite3

Ele contém informações relevantes para a definição do database.yml. Seus problemas com banco de dados podem ser decorrentes deste caso.

**Comment by prgs1** [comment]
esse link não serve pro nosso caso, nós não migramos do sqlite, já começamos com o postgresql.

dei um migrate e seed e pegou ;)
