### ISSUE TITLE
integrar api do Maps ao projeto

### ISSUE THREAD

**Issue by prgs1** [aplneto/medmapper#84]
Opção: [`gem 'gmap4rails'`]
Exemplos: https://apneadiving.github.io/

Opção: [API JavaScript do Google Maps](https://developers.google.com/maps/documentation/javascript/tutorial)
Exemplos na página.

[`gem 'gmap4rails'`]: https://github.com/apneadiving/Google-Maps-for-Rails

**Comment by isacits** [comment]
Finalizado em 1d6a9785e4d70485df19949e30aabbe36c00c1fe.
