### ISSUE TITLE
Feedback da IT3 ~ HU

### ISSUE THREAD

**Issue by aacgn** [aplneto/medmapper#87]
Oi pessoal,

Procurei na pasta da iteração 3 por histórias de usuários, mas não encontrei. Vocês podem me informar onde está localizado este artefato?

**Comment by aplneto** [comment]
Na iteração 3 as histórias de usuários que recebemos vieram principalmente de um grupo no WhatsApp que a cliente possui com outros profissionais. Se encontram principalmente [nesse arquivo](https://github.com/aplneto/medmapper/blob/master/docs/iteration3/COMENT%C3%81RIOS%20SOBRE%20O%20PROJETO%20(1).doc), mas também nas issues da Milestone iteration_3

**Comment by vinicius3w** [comment]
@aplneto eu dei uma olhada nas issues do milestone iteration_3. eles não são bem HUs, são tasks. podemos considerar que são "HUs de dev", técnicas... mas no caso estamos querendo ver as HUs do cliente sacou?

**Comment by isacits** [comment]
@vinicius3w a gente não documentou as Hu em uma sessão separada. Todas que temos foram direto da ata de reunião pro github. Até tentamos fazer a redação de histórias smart com a cliente, tendo um modelo na ata da reunião 2, mas nunca conseguimos adotar essa abordagem por parte dela e acabamos usando apenas para demonstrar quando alguma sugestão caia fora do escopo do projeto.

**Comment by aacgn** [comment]
Oi, pessoal.

Conversei com o @vinicius3w sobre a situações das HU de vocês e to passando aqui pra deixar o feedback.

Prazo | Critério | Avaliação | Nota
-- | -- | -- | --
22/05 | HU | Mesmo com a disponibilização do documento que é origem de atividades o seu registro como HU é obrigatório. É importante identificar o subconjunto de histórias trabalhadas na iteração e cadastra-las no Github com um responsável, utilizando as labels pre-definidas no projeto. Portanto, o máximo que conseguimos foi considerar o documento de origem como fonte de atividades 😿| 5.0
