### ISSUE TITLE
Edição do Readme.md

### ISSUE THREAD

**Issue by isacits** [aplneto/medmapper#9]
Editar o readme.md.
Modelos de referência:
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
https://github.com/dbader/readme-template

**Comment by aplneto** [comment]
Outros links úteis:

[Awsome readme](https://github.com/matiassingers/awesome-readme "Exemplos de repositórios com bons arquivoes Readme.md"), [Readme best practices](https://github.com/jehna/readme-best-practices "Práticas ao escrever um readme e template usado nesse repositório"), [Github Badges](https://nitratine.net/blog/post/github-badges/ "Guia de uso de badges no Github"), [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet "Planilha de consulta do Markdown")

![Logo Temporário](https://raw.githubusercontent.com/aplneto/projeto_ES/master/.idv/logotmp200x200.png "Logo temporário do projeto 200x200 pixels")

**Comment by aplneto** [comment]
Formatação do Readme finalizada.

**Comment by aplneto** [comment]
https://github.com/dwyl/repo-badges

**Comment by aplneto** [comment]
[Add badges later](https://github.com/dwyl/repo-badges)
